#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pushd $DIR/.. > /dev/null

if [ "$1" = '--use-docker' ]; then
  EMCC="docker run --rm -i -v $(pwd):/src -w /src trzeci/emscripten emcc"
else 
  EMCC=emcc
fi

# Extract the list of sources from the C target in the Swift package
SOURCES=$(swift package describe --type json | jq -r '.targets[] | select(.c99name == "CLibOpaque").sources[]')

$EMCC -O3 -msse2 -s WASM=1 -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap"]' -I Dependencies/argon2/include -I Dependencies/libecc/src -I Dependencies/tweetnacl -I Sources/CLibOpaque/include WebAssembly/libopaque.c $SOURCES

popd > /dev/null